services:
  - type: web
    name: domislink-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
  - type: web
    name: domislink-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
